apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: kubeprober
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-master
  namespace: kubeprober
  labels:
    app: probe-master
spec:
  selector:
    matchLabels:
      app: probe-master
  replicas: 1
  template:
    metadata:
      labels:
        app: probe-master
    spec:
      containers:
        - command:
            - /probe-master
          image: kubeprober/probe-master:v0.0.1
          imagePullPolicy: "Always"
          name: probe-master
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: kubeprober
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: probe-master
  namespace: kubeprober
  labels:
    name: probe-master
spec:
  ports:
    - port: 8088
      targetPort: 8088
      name: tcp
  selector:
    app: probe-master
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: kubeprober
rules:
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - clusters
  - clusters/status
  - probes
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubeprober
subjects:
  - kind: ServiceAccount
    name: kubeprober
    namespace: kubeprober
roleRef:
  kind: ClusterRole
  name: kubeprober
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeprober
  namespace: kubeprober