apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-agent
  namespace: system
  labels:
    app: probe-agent
spec:
  selector:
    matchLabels:
      app: probe-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: probe-agent
    spec:
      containers:
        - image: kubeprober/probe-agent:v0.0.1
          imagePullPolicy: "Always"
          name: probe-agent
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
          envFrom:
            - configMapRef:
                name: kubeprober
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: kubeprober
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: probeagent
  namespace: kubeprober
  labels:
    app: probe-agent
spec:
  selector:
    app: probe-agent
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: probe-status
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: health
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: pprof
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeprober
  namespace: system
data:
  PROBE_MASTER_ADDR: http://kubeprober-probe-master.kubeprober.svc.cluster.local:8088
  CLUSTER_NAME: moon
  SECRET_KEY: 2f5079a5-425c-4fb7-8518-562e1685c9b4