apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeprober-worker
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeprober-worker-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeprober-worker-role
subjects:
  - kind: ServiceAccount
    name: kubeprober-worker
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubeprober-worker-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - namespaces
    - pods
    - services
    - secrets
  verbs:
    - "*"
- apiGroups:
    - "apps"
  resources:
    - deployments
    - replicasets
  verbs:
    - "*"
- apiGroups:
    - "extensions"
  resources:
    - deployments
    - replicasets
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - "pods/exec"
  verbs:
    - "create"
- apiGroups:
    - "monitoring.coreos.com"
  resources:
    - servicemonitors
    - podmonitors
    - prometheus
    - prometheuses
  verbs:
    - "*"