apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeprober-readonly
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeprober-readonly-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeprober-readonly-role
subjects:
  - kind: ServiceAccount
    name: kubeprober-readonly
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubeprober-readonly-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]