
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probes/finalizers
  verbs:
  - update
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probestatuses/finalizers
  verbs:
  - update
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probestatuses/status
  verbs:
  - get
  - patch
  - update
