apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: kubeprober
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-agent
  namespace: kubeprober
  labels:
    app: probe-agent
spec:
  selector:
    matchLabels:
      app: probe-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: probe-agent
    spec:
      containers:
        - image: kubeprober/probe-agent:v0.0.1
          imagePullPolicy: "Always"
          name: probe-agent
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
          envFrom:
          - configMapRef:
              name: kubeprober
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccountName: kubeprober
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: probeagent
  namespace: kubeprober
  labels:
    app: probe-agent
spec:
  selector:
    app: probe-agent
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: probe-status
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: health
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: pprof
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeprober
  namespace: kubeprober
data:
  PROBE_MASTER_ADDR: http://10.107.114.92:8088
  CLUSTER_NAME: moon
  SECRET_KEY: a944499f-97f3-4986-89fa-bc7dfc7e009a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: kubeprober
rules:
  - apiGroups:
      - kubeprober.erda.cloud
    resources:
      - clusters
      - clusters/status
      - probes
      - probes/status
      - probestatuses
      - probestatuses/status
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubeprober
subjects:
  - kind: ServiceAccount
    name: kubeprober
    namespace: kubeprober
roleRef:
  kind: ClusterRole
  name: kubeprober
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeprober
  namespace: kubeprober