apiVersion: kubeprober.erda.cloud/v1
kind: Probe
metadata:
  name: probe-cron-sample
spec:
  policy:
    # unit: minute
    runInterval: 2
  # Add fields here
  probeList:
    # Probe item1
    - name: probe-cron-item1
      spec:
        containers:
          - name: demo-error
            image: kubeprober/probe-test-demo-error:v0.0.1
        restartPolicy: Never
