apiVersion: kubeprober.erda.cloud/v1alpha1
kind: Probe
metadata:
  name: probe-cron-sample
spec:
  policy:
    # unit: minute
    runInterval: 1
  # Add fields here
  probeList:
    # Probe item1
    - name: probe-cron-item1
      spec:
        containers:
          - name: hello
            image: busybox
            command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 10']
        restartPolicy: Never
