apiVersion: kubeprober.erda.cloud/v1
kind: Probe
metadata:
  name: probe-cron-link-test
spec:
  policy:
    # unit: minute
    runInterval: 2
  probeList:
    # probe item1:
    - name: item1-dns-resolution-check
      spec:
        containers:
          - env:
              - name: HOSTNAME
                value: "kubernetes.default"
              - name: NAMESPACE
                value: "kube-system"
              - name: DNS_NODE_SELECTOR
                value: apps=k8s-dns
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            name: dns-resolution-check
            image: kubeprober/dns-resolution-check:v0.0.1
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
        restartPolicy: Never
    # probe item2: probe status with level -- INFO
    - name: item2-demo-info
      spec:
        containers:
          - name: demo-info
            image: kubeprober/demo-info:v0.0.1
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
        restartPolicy: Never