apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-master
  namespace: system
  labels:
    app: probe-master
spec:
  selector:
    matchLabels:
      app: probe-master
  replicas: 1
  template:
    metadata:
      labels:
        app: probe-master
    spec:
      containers:
        - command:
            - /probe-master
          env:
            - name: SERVER_SECRET_KEY
              value: your-token-here
          image: kubeprober/probe-master:v0.0.3
          imagePullPolicy: "Always"
          name: probe-master
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: kubeprober
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: probe-master
---
apiVersion: v1
kind: Service
metadata:
  name: probe-master
  namespace: system
  labels:
    name: probe-master
spec:
  ports:
    - port: 8088
      targetPort: 8088
      name: tcp
  selector:
    app: probe-master
