apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-master
  namespace: system
  labels:
    app: probe-master
spec:
  selector:
    matchLabels:
      app: probe-master
  replicas: 1
  template:
    metadata:
      labels:
        app: probe-master
    spec:
      containers:
        - image: kubeprober/probe-master:v0.1.0-beta24
          imagePullPolicy: "Always"
          command: ["/bin/sh"]
          args: ["-c", "/probe-master --config-file=/opt/probe-master-conf.yaml"]
          env:
            - name: SERVER_SECRET_KEY
              value: your-token-here
          name: probe-master
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - name: probe-master-config-volume
              mountPath: /opt
      volumes:
        - name: probe-master-config-volume
          configMap:
            name: probemaster
      serviceAccountName: kubeprober
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: probemaster
  namespace: system
data:
  probe-master-conf.yaml: |
      influxdb_enable: false
      influxdb_host:
      influxdb_token:
      influxdb_org:
      influxdb_bucket:
      erda_ticket_enable: false
      erda_openapi_url:
      erda_username:
      erda_password:
      erda_org:
      erda_project_id:
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: probe-master
---
apiVersion: v1
kind: Service
metadata:
  name: probe-master
  namespace: system
  labels:
    name: probe-master
spec:
  ports:
    - port: 8088
      targetPort: 8088
      name: tcp
  selector:
    app: probe-master
