apiVersion: kubeprober.erda.cloud/v1
kind: Probe
metadata:
  name: k8s
  namespace: kubeprober
spec:
  policy:
    # unit: minute
    runInterval: 2
  template:
    containers:
      - name: k8s
        image: kubeprober/node-check:v0.0.3
        env:
          - name: PROBE_LIST
            value: "node_ready.sh"
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
    restartPolicy: Never