name: PR Build and Merge Validation

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Make controller-gen
        run: make controller-gen

      - name: Build
        env:
          APP: probe-master
        run: make build

      - name: Check build status
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed. PR cannot be merged."
            exit 1
          fi
