name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Read version file
      id: version
      run: echo "::set-output name=version::$(cat version)"

    - name: Make controller-gen
      run: make controller-gen

    - name: Build Docker image
      run: APP=probe-master V=${{ steps.version.outputs.version }} make docker-build
